### ISSUE TITLE
Remove Experimental Warning for Dynamic Theme

### ISSUE THREAD

**Issue by megamorphg** [victor-savinov/dark-mode#14]
I turn on dark mode on a per-website basis and this latest "Dynamic theme" feature is awesome. As it works fine, can we remove the warning?
![image](https://user-images.githubusercontent.com/1782353/135271496-3fb93f67-ee9b-4dca-b5c0-28968f8b2d02.png)

Every time I turn it on for a website I have to see the warning but I don't think it is necessary anymore because it works great! 👍

**Comment by victor-savinov** [comment]
https://github.com/victor-savinov/dark-mode/commit/93af65c13220964885f9e91ebf857b9d3d12d436
