### ISSUE TITLE
add dark mode to settings

### ISSUE THREAD

**Issue by wadawada** [victor-savinov/dark-mode#4]
Consider the extension is made to darken websites
switching on/off frequently will create too much flashing in the UI
so would be great to have a "always in dark mode UI" setting

**Comment by ImprovedTube** [comment]
hi @wadawada, happy 2021!  
you can enable dark (inversion only just yet) globally too (and per website). 
the extension's "power switch" is not required.
How would it be more intutive?

**Comment by wadawada** [comment]
I think you don't understand what I meant
people who want dark mode means they want less flashing to the eyes
so on/off switch animation of white <-> black is unnecessary
It would be best to just keep the menu black all the time

**Comment by ImprovedTube** [comment]
@wadawada  oh. long time no read.   
you make sense 🤔 just saying it is like a power-off switch though. Maybe it is fun at first. Disabling everything. never need it with more precise settings. can be designed more intuitively?  (without it some people would deinstall it in a hurry before understanding more) 
Permanent users can have a schedule and global filters on most pages always (never need the master switch)
 (filters: global: inversion and/or bluelight filter.  this  takes two clicks too much currently compared to having that global filter on the front page)     - Then all left to do is to exclude some pages from that    (or report those page's issues, so they could be fixed universally)

**Comment by victor-savinov** [comment]
Now only dark theme

**Comment by ImprovedTube** [comment]
a sudden fullscreen flash to white is blinding, even when intentionally triggered.
so the animation is a nice transition, if it comes simultanously with the change on the page, or slightly earlier.       that would help when switching off dark mode on a site or whole Extension, 
Our UI's sunny view will be at the user's focus and can be slightly/less blinding, yellowish/not 100% bright.  i.e. #FEA, but still a functioning transition.

(While, witching off the lights,  a sudden darkness would be ok but animation could also be relaxing, since what happens in the extension is just small part of the screen.)

**Comment by ImprovedTube** [comment]
a sudden fullscreen flash to white can be blinding, even when intentionally triggered.
the animation was a nice transition, whencoming simultanously with the change on the page, or slightly earlier and almost done when the page changes.   
(it helps most when switching off dark mode on a site or whole Extension)
Our UI's sunny view can be slightly/less blinding then white and i.e. #FEA, 

the movement mainly guides the focus back to the page. 
for relaxion, the color on the whole page and popup could also fade over, so no flash at all

switching off the lights, of course isnt blinding but the same effect reverse could again guide the eyes nad confirm the action.

**Comment by ImprovedTube** [comment]
a sudden fullscreen flash to white can be blinding, even when intentionally triggered.
(when switching off dark mode on a site or whole Extension. Our UI's lights-on/sunny-view can be slightly/less blinding than white, i.e. #FEA.   switching off the lights, of course isnt blinding but the same effect reverse again guides the eyes and confirms the intention) 
- The animation was a nice transition, when coming simultanously with the change on the page, or slightly earlier and almost done when the page changes.   

Yet the movement mainly guides the focus back to the page. 
for relaxion, the color on the whole page (and popup) could rather fade over, so no flash.
