### ISSUE TITLE
Domain exceed width

### ISSUE THREAD

**Issue by aleluff** [victor-savinov/dark-mode#5]
Hi,

First thanks and congrats for the job

![image](https://user-images.githubusercontent.com/3399495/109731409-7c555500-7bbb-11eb-892f-7bf820dbd2e9.png)
Can you solve this bug please

Tell me if you need some hands =)

**Comment by victor-savinov** [comment]
Fixed (https://github.com/victor-savinov/dark-mode/commit/9b56ba95e49e693fa5d3dd6308ce83d40d92d096)
